[workspace]
members = ["derive"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
authors = ["Marin Veršić <marin.versic101@gmail.com>"]

[package]
name = "rust-spec"

version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

description = "Classification of types in accordance with the Rust specification"
repository = "https://github.com/mversic/rust-spec"
keywords = ["rust", "specification", "classification", "layout", "repr"]

categories = ["rust-patterns", "no-std"]

[features]
# Implement classification for types from the `alloc` crate (e.g. `Box<T>` or `Vec<T>`).
alloc = ["rust-spec-derive?/alloc"]

# Enables `#[derive(RustSpec)]`
derive = ["rust-spec-derive"]

default = ["alloc", "derive"]

[dependencies]
rust-spec-derive = { path = "derive", optional = true }

disjoint_impls = "1.3.8"

[dev-dependencies]
static_assertions = "1.1.0"
