[package]
name = "rust-spec"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
authors = ["Marin Veršić <marin.versic101@gmail.com>"]
repository = "https://github.com/mversic/co3"
description = "Rust-specified type property traits for co3"

[features]
default = ["alloc"]
alloc = []
derive = ["rust-spec-derive"]

[dependencies]
rust-spec-derive = { path = "derive", optional = true }
disjoint_impls = { path = "../../disjoint_impls/" }

[dev-dependencies]
static_assertions = "1.1.0"
