[package]
name = "rust-spec-derive"

version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

description = "Derive macros for `rust-spec`"
repository = "https://github.com/mversic/rust-spec"

[lib]
proc-macro = true

[dependencies]
syn = { version = "3.0.6", features = ["visit", "extra-traits"] }
proc-macro-crate = "3.5.0"
proc-macro2 = "1.0.107"
quote = "1.0.47"
