name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v7
    - uses: Swatinem/rust-cache@v2
    - uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy

    - name: Rust format
      run: cargo fmt --check

    - name: Check workspace
      run: cargo check --workspace

    - name: Link workspace
      run: cargo clippy -- --deny warnings

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v7
    - uses: Swatinem/rust-cache@v2
    - uses: dtolnay/rust-toolchain@stable

    - name: Run tests
      run: cargo test --workspace
