name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy
    - uses: Swatinem/rust-cache@v2

    - name: Rust format
      run: cargo fmt --check

    - name: Clippy (all features)
      run: cargo clippy --all-features -- --deny warnings

    - name: Clippy (no features)
      run: cargo clippy --no-default-features -- --deny warnings

  check:
    runs-on: ${{ matrix.os }}
    needs: static-analysis
    timeout-minutes: 5

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - uses: Swatinem/rust-cache@v2
      with:
        key: check-${{ matrix.os }}

    - name: Check (all features)
      run: cargo check --all-features

    - name: Check (no features)
      run: cargo check --no-default-features

  wasm-check:
    runs-on: ubuntu-latest
    needs: static-analysis
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-wasip1
      - uses: Swatinem/rust-cache@v2

      - name: Check (WASIp1)
        run: cargo check --target wasm32-wasip1 --all-features
